= Change Log

All notable changes to this project will be documented in this file.

== 1.6-SNAPSHOT - 2014-10-02

=== Changed
- We broke Maven 3.0.x ( and thus, IntelliJ ) support again with the changes
  to the thunked inheritance merger. Further investigation reveals this
  behaviour is broken under Maven even without tiles, but only affects the
  effective-pom - so has been removed.

== 1.5 - 2014-10-01

=== Changed
- When 1.4 switched to the new 'parental guidance' model of applying
  tiles, we unfortunately missed a critical step of applying activated
  and deactivate profiles, as well as the superpom. This meant that
  all unconfigured plugins simply..... vanished.
- As part of the above change, a problem dating back to 1.3 where
  `<configuration>` blocks that were not inside a plugins `<execution>`
  block were not correctly being applied to the plugin.

== 1.4 - 2014-09-29

=== Added
- The Maven Tiles Plugin now supports `<pluginManagement>` and `<profiles>`
  declared inside of a tile.


=== Changed
- Major internal reworking of how tiles are applied. Each tile is now
  injected into your POM's Model as a parent artifact, with your `pom.xml`'s
  original parent being used as the top level parent of the root tile.
- `<buildSmells>` configuration is now used at tile release time.

== 1.3 - 2014-09-24

=== Added
- Apache Maven configuration parameter defintions for IDE support.
  This prevents IDEs such as IntelliJ IDEA from reporting `<tiles>`
  as being unexpected content.

=== Changed
- Added fallback support for Apache Maven 3.0.x. Primarilly to support
  working within IntelliJ IDEA which embeds 3.0.x. This means that tiles
  based projects resolve in the IDE correctly, once again letting you
  _develop with pleasure_.


== 1.2 - 2014-09-23

=== Changed
- Fixed faulty merging of `<dependencyManagement>` sections from parent POMs
  when the tiles plugin was included in your project POM.

