= Tiles Maven Plugin

== Contributing

Please take a moment to review this document in order to make the contribution process
easy and effective for everyone involved.

=== Using the issue tracker

The https://github.com/repaint-io/maven-tiles/issues[issue tracker] is
the preferred channel for reporting all bugs or feature requests for the
plugin.

* Please **do not** use the issue tracker for personal support requests.

* Please **do not** use the issue tracker for general http://maven.apache.org[Apache Maven]
  related issues.

* Please **do not** derail or troll issues. Keep the discussion on topic and
  respect the opinions of others.

=== Submitting a patch

Pull requests are accepted and managed via Github but please respect the following restrictions:

NOTE: **IMPORTANT**: By submitting a patch, you agree to allow the project owners to
license your work under the terms of the Apache 2.0 License.

Please do not over-commit, make each commit meaningful and consider squashing your commits. We may
ask you to do that before considering merging your commit. Our ideal is one commit per
issue if possible.


