name: Integration Tests on Java 21

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
      - name: Switch To Maven 3
        run: |
          echo "distributionUrl=https://archive.apache.org/dist/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip" > .mvn/wrapper/maven-wrapper.properties
          echo "wrapperVersion=3.3.2" >> .mvn/wrapper/maven-wrapper.properties
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots install -Prun-its
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: it-build-logs
          path: target/it
