name: Integration Tests on Java 22 and Maven 4.0.0-beta-4

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 22
      - name: Switch To Maven 4
        run: |
          echo "distributionUrl=https://dlcdn.apache.org/maven/maven-4/4.0.0-rc-3/binaries/apache-maven-4.0.0-rc-3-bin.zip" > .mvn/wrapper/maven-wrapper.properties
          echo "wrapperVersion=3.3.2" >> .mvn/wrapper/maven-wrapper.properties
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots install -Prun-its
