name: Integration Tests on Java 21

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Switch To Maven 3
        run: |
          echo "distributionUrl=https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.zip" > .mvn/wrapper/maven-wrapper.properties
          echo "wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.2.0/maven-wrapper-3.2.0.jar" >> .mvn/wrapper/maven-wrapper.properties
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots install -Prun-its
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: it-build-logs
          path: target/it
